name: Dependabot Auto-Merge
on:
  pull_request:
    types: [opened, synchronize, reopened]
  check_suite:
    types: [completed]

permissions:
  pull-requests: write
  contents: write

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Wait for CI to be green
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            if (!pr) return;
            const { data: checks } = await github.checks.listForRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: pr.head.sha,
            });
            const allPass = checks.check_runs.every(c => c.conclusion === 'success' || c.conclusion === 'neutral' || c.status !== 'completed');
            if (!allPass) {
              core.setFailed('CI not green yet');
            }

      - name: Enable auto-merge
        uses: peter-evans/enable-pull-request-automerge@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash
